// <auto-generated />
using System;
using BankManagmentSystem.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BankManagmentSystem.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20210625064222_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BankManagmentSystem.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("accounttype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("branchname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("citizenship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("citizenshipstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("contactnumber")
                        .HasColumnType("bigint");

                    b.Property<string>("country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dateofbirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guardianname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("guardiantype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("idcardnumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("initialdeposit")
                        .HasColumnType("bigint");

                    b.Property<string>("maritalstatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("referenceaccountholderaccountnumber")
                        .HasColumnType("bigint");

                    b.Property<string>("referenceaccountholderaddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("referenceaccountholdername")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("registrationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("state")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("useraccount")
                        .HasColumnType("bigint");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
